version: '3.9'

services:
  # MongoDB services
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    # ports: 27017
    volumes:
      - mongo_db:/data/db
  # NodeJS API servives
  api:
    container_name: api_container
    build: .
    ports:
      - 6000:3000
    environment:
      PORT: 3000
      MONGO_URL: mongodb://mongo_db:27017/ChatAPP
      TOKEN_EXPIRY: 24h
      SECRET_KEY: amit
      NODE_ENV: development
      MESSAGE_LIMIT: 20
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
